# Navigation
nav:
  Главная: /
  Книги: books
  Надписи: inscriptions
  Видео: video
  Желаемое: wishlist
  О: about

# Site
title: podabed.org
subtitle: ">3"
description: Блог коваля.
author: Dmitrij Podabed
language: ru
timezone: Asia/Krasnoyarsk

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://podabed.org
root: ""
permalink: blog/:day-:month-:year-:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :year-:month-:day-:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: true
future: false
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: "обо всём"
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: DD.MM.YYYY
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: default

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:

# Minify
html_minifier:
  enable: true
  exclude: 

css_minifier:
  enable: true
  exclude: 
    - "*.min.css"

js_minifier:
  enable: true
  mangle: true
  output:
  compress:
  exclude: 
    - "*.min.js"

image_minifier:
  enable: true
  interlaced: true
  multipass: true
  optimizationLevel: 7
  pngquant: true
  progressive: true

# Autoprefixer
autoprefixer:
  exclude:
    - "*.min.css"
  browsers:
    - "last 10 versions"

# Archive gen
archive_generator:
  per_page: 10
  yearly: true
  monthly: true
  daily: false

# Category gen
category_generator:
  per_page: 10

# Feed gen
feed:
  type: atom
  path: atom.xml
  limit: false
  hub:
  content: true

# Index gen
index_generator:
  per_page: 10
  order_by: -date

# Sitemap gen
sitemap:
  path: sitemap.xml
  template: ./sitemap_template.xml

# node_sass
node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false