name: Build And Deploy

on:
  push:
    branches:
      - source
run-name: Build And Deploy

jobs:
  build-and-deploy:
    name: Build And Deploy
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          git_commit_gpgsign: true
          git_user_signingkey: true
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        name: GitHub Pages Deploy
        uses: crazy-max/ghaction-github-pages@v4
        with:
          author: Dzmitry Padabed <itfarrier@icloud.com>
          build_dir: public
          commit_message: Updates
          committer: Dzmitry Padabed <itfarrier@icloud.com>
          fqdn: itfarrier.github.io
          keep_history: true
          target_branch: master
          verbose: true
